name: butterfly
version: 0.0.2
authors:
- Yegor Jbanov <yjbanov@google.com>
description: >
  A web framework for Dart based on Flutter's widget model. The goal of the
  project is conceptual and data model compatibility with Flutter. An explicit
  non-goal is "write once, run anywhere".
homepage: https://github.com/yjbanov/butterfly
environment:
  sdk: '>=1.14.0 <2.0.0'
dependencies:
  browser: ^0.10.0+2
dev_dependencies:
  test: '>=0.12.0 <1.0.0'
  charcode:
  quiver:

transformers:
- $dart2js:
    minify: true
